# config.yml
download:
    max_concurrent: 1
    retry_attempts: 5
    retry_delay: 3
    verify_ssl: false
    progress_increment: 1  # Show progress every X percent (between 1-100)

db1b_market:
    enabled: true
    base_url: "https://transtats.bts.gov/PREZIP/Origin_and_Destination_Survey_DB1BMarket"
    years: [2024...2024]
    quarters: [1]

db1b_coupon:
    enabled: true
    base_url: "https://transtats.bts.gov/PREZIP/Origin_and_Destination_Survey_DB1BCoupon"
    years: [2024]
    quarters: [1]
    max_segments: 4
    min_connection_minutes: 30
    max_connection_minutes: 1440